# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

steps:
# build the container
- name: 'gcr.io/cloud-builders/docker'
  env:
    - '_SECRET_KEY=$_SECRET_KEY'
  args: 
    - build
    - '--network=cloudbuild'
    - '-t'
    - 'gcr.io/$PROJECT_ID/base'
    - '--build-arg=_SECRET_KEY=${_SECRET_KEY}'
    - .

# create .env file
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "createenv"]
  env:
   - 'SECRET_KEY=${_SECRET_KEY}'
   - '_SECRET_KEY=${_SECRET_KEY}'

# Print Node.js version.
- name: 'gcr.io/$PROJECT_ID/base'
  entrypoint: 'node'
  args: ['--version']

# Print npm version.
- name: 'gcr.io/$PROJECT_ID/base'
  entrypoint: 'npm'
  args: ['--version']

# import dotenv.
- name: 'gcr.io/$PROJECT_ID/base'
  entrypoint: 'npm'
  args: ['install', 'dotenv']

# Build project.
- name: 'gcr.io/$PROJECT_ID/base'
  entrypoint: 'npm'
  args: ['run', 'build']

# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/base']

# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'sample-server', '--image', 'gcr.io/$PROJECT_ID/base', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

# Run server.
#- name: 'gcr.io/$PROJECT_ID/base'
#  entrypoint: 'npm'
#  args: ['run', 'start']

images: ['gcr.io/$PROJECT_ID/base']
