# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/base', '.']

# Print Node.js version.
- name: 'gcr.io/$PROJECT_ID/base'
  entrypoint: 'node'
  args: ['--version']

# Print npm version.
- name: 'gcr.io/$PROJECT_ID/base'
  entrypoint: 'npm'
  args: ['--version']

# Build project.
- name: 'gcr.io/$PROJECT_ID/base'
  entrypoint: 'npm'
  args: ['run', 'build']

# Run server.
- name: 'gcr.io/$PROJECT_ID/base'
  entrypoint: 'npm'
  args: ['run', 'start']

images: ['gcr.io/$PROJECT_ID/base']