# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

steps:
# build the container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--network=cloudbuild','-t', 'gcr.io/$PROJECT_ID/base', '.']

# create .env file
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "createenv"]
  env:
   - 'SECRET_KEY=${_SECRET_KEY}'

# Print Node.js version.
- name: 'gcr.io/$PROJECT_ID/base'
  entrypoint: 'node'
  args: ['--version']

# Print npm version.
- name: 'gcr.io/$PROJECT_ID/base'
  entrypoint: 'npm'
  args: ['--version']

# Build project.
- name: 'gcr.io/$PROJECT_ID/base'
  entrypoint: 'npm'
  args: ['run', 'build']

# Run server.
- name: 'gcr.io/$PROJECT_ID/base'
  entrypoint: 'npm'
  args: ['run', 'start']

images: ['gcr.io/$PROJECT_ID/base']